; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64

define void @inlineasm(i32 %a, i32 %b, ptr %ptr) {
; X64-LABEL: <inlineasm>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    int3
; X64-NEXT:    mov dword ptr [rbp - 0x2c], esi
; X64-NEXT:    mov qword ptr [rbp - 0x38], rdx
; X64-NEXT:    mov eax, edi
; X64-NEXT:    mov rsi, rbx
; X64-NEXT:    cpuid
; X64-NEXT:    xchg rbx, rsi
; X64-NEXT:    mov rbx, qword ptr [rbp - 0x38]
; X64-NEXT:    mov dword ptr [rbx], eax
; X64-NEXT:    mov dword ptr [rbx + 0x4], esi
; X64-NEXT:    mov dword ptr [rbx + 0x8], ecx
; X64-NEXT:    mov dword ptr [rbx + 0xc], edx
; X64-NEXT:    mov eax, edi
; X64-NEXT:    mov ecx, dword ptr [rbp - 0x2c]
; X64-NEXT:    mov rsi, rbx
; X64-NEXT:    cpuid
; X64-NEXT:    xchg rbx, rsi
; X64-NEXT:    mov dword ptr [rbx], eax
; X64-NEXT:    mov dword ptr [rbx + 0x4], esi
; X64-NEXT:    mov dword ptr [rbx + 0x8], ecx
; X64-NEXT:    mov dword ptr [rbx + 0xc], edx
; X64-NEXT:    mov ecx, edi
; X64-NEXT:    xgetbv
; X64-NEXT:    mov dword ptr [rbx], eax
; X64-NEXT:    mov dword ptr [rbx + 0x4], edx
; X64-NEXT:    pop rbx
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  call void asm "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm sideeffect "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm unwind "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm sideeffect "", "~{memory},~{dirflag},~{fpsr},~{flags}"()
  call void asm unwind "", "~{memory},~{dirflag},~{fpsr},~{flags}"()
  call void asm sideeffect "int3", "~{dirflag},~{fpsr},~{flags}"()

  %cpuid = call { i32, i32, i32, i32 } asm "movq\09%rbx, %rsi\0A\09cpuid\0A\09xchgq\09%rbx, %rsi\0A\09", "={ax},={si},={cx},={dx},{ax},~{dirflag},~{fpsr},~{flags}"(i32 %a)
  store { i32, i32, i32, i32 } %cpuid, ptr %ptr
  %cpuid2 = call { i32, i32, i32, i32 } asm "movq\09%rbx, %rsi\0A\09cpuid\0A\09xchgq\09%rbx, %rsi\0A\09", "={ax},={si},={cx},={dx},{ax},{cx},~{dirflag},~{fpsr},~{flags}"(i32 %a, i32 %b)
  store { i32, i32, i32, i32 } %cpuid2, ptr %ptr
  %xgetbv = call { i32, i32 } asm ".byte 0x0f, 0x01, 0xd0", "={ax},={dx},{cx},~{dirflag},~{fpsr},~{flags}"(i32 %a)
  store { i32, i32 } %xgetbv, ptr %ptr

  ret void
}
