; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2026 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

define i32 @getrounding() {
; X64-LABEL: <getrounding>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x2
; X64-NEXT:    fnstcw word ptr [rsp]
; X64-NEXT:    movzx ecx, word ptr [rsp]
; X64-NEXT:    shr ecx, 0x9
; X64-NEXT:    and cl, 0x6
; X64-NEXT:    mov eax, 0x2d
; X64-NEXT:    shr eax, cl
; X64-NEXT:    and eax, 0x3
; X64-NEXT:    add rsp, 0x2
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <getrounding>:
; ARM64:         mrs x0, FPCR
; ARM64-NEXT:    add w0, w0, #0x400, lsl #12 // =0x400000
; ARM64-NEXT:    ubfx w1, w0, #22, #2
; ARM64-NEXT:    mov w0, w1
; ARM64-NEXT:    ret
  %r = call i32 @llvm.get.rounding()
  ret i32 %r
}
