; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2026 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1

define { float, i32 } @frexpf32(float %a) {
; X64-LABEL: <frexpf32>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x30
; X64-NEXT:    lea rax, [rbp - 0x2c]
; X64-NEXT:    mov rdi, rax
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 frexpf-0x4
; X64-NEXT:  <L0>:
; X64-NEXT:    mov eax, dword ptr [rbp - 0x2c]
; X64-NEXT:    add rsp, 0x30
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <frexpf32>:
; ARM64:         stp x29, x30, [sp, #-0xb0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    add x0, x29, #0xa4
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    bl <L0>
; ARM64-NEXT:     R_AARCH64_CALL26 frexpf
; ARM64-NEXT:    ldr w0, [x29, #0xa4]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xb0
; ARM64-NEXT:    ret
  %r = call { float, i32 } @llvm.frexp(float %a)
  ret { float, i32 } %r
}

define { double, i32 } @frexpf64(double %a) {
; X64-LABEL: <frexpf64>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x40
; X64-NEXT:    lea rax, [rbp - 0x38]
; X64-NEXT:    mov rdi, rax
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 frexp-0x4
; X64-NEXT:  <L0>:
; X64-NEXT:    mov eax, dword ptr [rbp - 0x38]
; X64-NEXT:    add rsp, 0x40
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <frexpf64>:
; ARM64:         stp x29, x30, [sp, #-0xb0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    add x0, x29, #0xa8
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    bl <L0>
; ARM64-NEXT:     R_AARCH64_CALL26 frexp
; ARM64-NEXT:    ldr w0, [x29, #0xa8]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xb0
; ARM64-NEXT:    ret
  %r = call { double, i32 } @llvm.frexp(double %a)
  ret { double, i32 } %r
}
