; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1

declare float @llvm.nearbyint.f32(float)
declare double @llvm.nearbyint.f64(double)

define float @nearbyintf32(float %0) {
; X64-LABEL: <nearbyintf32>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x30
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 nearbyintf-0x4
; X64-NEXT:  <L0>:
; X64-NEXT:    add rsp, 0x30
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <nearbyintf32>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    bl <L0>
; ARM64-NEXT:     R_AARCH64_CALL26 nearbyintf
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  %1 = call float @llvm.nearbyint.f32(float %0)
  ret float %1
}

define double @nearbyintf64(double %0) {
; X64-LABEL: <nearbyintf64>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x30
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 nearbyint-0x4
; X64-NEXT:  <L0>:
; X64-NEXT:    add rsp, 0x30
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <nearbyintf64>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    bl <L0>
; ARM64-NEXT:     R_AARCH64_CALL26 nearbyint
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  %1 = call double @llvm.nearbyint.f64(double %0)
  ret double %1
}
