; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2026 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1
; XFAIL: llvm21.1

; Note: ptrtoaddr integer bit width must match pointer size.

define i64 @ptrtoaddr_i64(ptr %0) {
; X64-LABEL: <ptrtoaddr_i64>:
; X64:         mov rax, rdi
; X64-NEXT:    ret
;
; ARM64-LABEL: <ptrtoaddr_i64>:
; ARM64:         ret
  entry:
  %1 = ptrtoaddr ptr %0 to i64
  ret i64 %1
}

define i64 @ptrtoaddr_i64_no_salvage(ptr %0) {
; X64-LABEL: <ptrtoaddr_i64_no_salvage>:
; X64:         mov rax, rdi
; X64-NEXT:    mov rax, rdi
; X64-NEXT:    ret
;
; ARM64-LABEL: <ptrtoaddr_i64_no_salvage>:
; ARM64:         mov x1, x0
; ARM64-NEXT:    ret
  entry:
  %1 = ptrtoaddr ptr %0 to i64
  %2 = ptrtoaddr ptr %0 to i64
  ret i64 %2
}

define <2 x i64> @ptrtoaddr_v2i64(<2 x ptr> %p) {
; X64-LABEL: <ptrtoaddr_v2i64>:
; X64:         ret
;
; ARM64-LABEL: <ptrtoaddr_v2i64>:
; ARM64:         ret
  %r = ptrtoaddr <2 x ptr> %p to <2 x i64>
  ret <2 x i64> %r
}

define void @ptrtoaddr_v6i64(ptr %p, ptr %q) {
; X64-LABEL: <ptrtoaddr_v6i64>:
; X64:         movups xmm0, xmmword ptr [rdi]
; X64-NEXT:    movups xmm1, xmmword ptr [rdi + 0x10]
; X64-NEXT:    movups xmm2, xmmword ptr [rdi + 0x20]
; X64-NEXT:    movups xmmword ptr [rsi], xmm0
; X64-NEXT:    movups xmmword ptr [rsi + 0x10], xmm1
; X64-NEXT:    movups xmmword ptr [rsi + 0x20], xmm2
; X64-NEXT:    ret
;
; ARM64-LABEL: <ptrtoaddr_v6i64>:
; ARM64:         ldr q0, [x0]
; ARM64-NEXT:    ldr q1, [x0, #0x10]
; ARM64-NEXT:    ldr q2, [x0, #0x20]
; ARM64-NEXT:    str q0, [x1]
; ARM64-NEXT:    str q1, [x1, #0x10]
; ARM64-NEXT:    str q2, [x1, #0x20]
; ARM64-NEXT:    ret
  %l = load <6 x ptr>, ptr %p
  %r = ptrtoaddr <6 x ptr> %l to <6 x i64>
  store <6 x i64> %r, ptr %q
  ret void
}
